events {}

http {
    upstream core_api {
        server core-api:3001;
    }

    upstream service_api {
        server service-api:3002;
    }

    upstream web_app {
        server web:80;
    }

    server {
        listen 80;

        location /api/core/ {
            proxy_pass http://core_api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/service/ {
            proxy_pass http://service_api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://web_app;
            proxy_set_header Host $host;
        }
    }
}